# Generated by Django 6.0.6 on 2026-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(default=1000, max_length=100),
            preserve_default=False,
        ),
    ]
